# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'training.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 590)
        self.listWidget_training = QtWidgets.QListWidget(Dialog)
        self.listWidget_training.setGeometry(QtCore.QRect(30, 300, 851, 231))
        self.listWidget_training.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_training.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_training.setAutoScrollMargin(40)
        self.listWidget_training.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listWidget_training.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_training.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_training.setObjectName("listWidget_training")
        self.btn_Clear = QtWidgets.QPushButton(Dialog)
        self.btn_Clear.setGeometry(QtCore.QRect(30, 540, 89, 25))
        self.btn_Clear.setObjectName("btn_Clear")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 340, 210))
        self.groupBox.setObjectName("groupBox")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 41, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_batch = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_batch.setGeometry(QtCore.QRect(120, 30, 113, 25))
        self.lineEdit_batch.setObjectName("lineEdit_batch")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 91, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_subdivision = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_subdivision.setGeometry(QtCore.QRect(120, 60, 113, 25))
        self.lineEdit_subdivision.setObjectName("lineEdit_subdivision")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 91, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_learnRate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_learnRate.setGeometry(QtCore.QRect(120, 90, 113, 25))
        self.lineEdit_learnRate.setObjectName("lineEdit_learnRate")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 120, 91, 17))
        self.label_9.setObjectName("label_9")
        self.lineEdit_max_batches = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_max_batches.setGeometry(QtCore.QRect(120, 120, 113, 25))
        self.lineEdit_max_batches.setObjectName("lineEdit_max_batches")
        self.btn_Config = QtWidgets.QPushButton(self.groupBox)
        self.btn_Config.setGeometry(QtCore.QRect(240, 180, 89, 25))
        self.btn_Config.setObjectName("btn_Config")
        self.btn_checkCurrent = QtWidgets.QPushButton(self.groupBox)
        self.btn_checkCurrent.setGeometry(QtCore.QRect(240, 30, 89, 25))
        self.btn_checkCurrent.setObjectName("btn_checkCurrent")
        self.lineEdit_filter = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_filter.setEnabled(True)
        self.lineEdit_filter.setGeometry(QtCore.QRect(120, 180, 113, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_filter.setFont(font)
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.lineEdit_classes = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_classes.setEnabled(True)
        self.lineEdit_classes.setGeometry(QtCore.QRect(120, 150, 113, 25))
        font = QtGui.QFont()
        font.setItalic(True)
        self.lineEdit_classes.setFont(font)
        self.lineEdit_classes.setObjectName("lineEdit_classes")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 150, 91, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 180, 91, 17))
        self.label_11.setObjectName("label_11")
        self.btn_convert = QtWidgets.QPushButton(self.groupBox)
        self.btn_convert.setGeometry(QtCore.QRect(240, 80, 89, 25))
        self.btn_convert.setObjectName("btn_convert")
        self.btn_make = QtWidgets.QPushButton(self.groupBox)
        self.btn_make.setGeometry(QtCore.QRect(240, 120, 89, 25))
        self.btn_make.setObjectName("btn_make")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 20, 501, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidget_yolodata = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_yolodata.setGeometry(QtCore.QRect(10, 60, 221, 141))
        self.listWidget_yolodata.setObjectName("listWidget_yolodata")
        self.listWidget_yoloNames = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget_yoloNames.setGeometry(QtCore.QRect(260, 60, 221, 141))
        self.listWidget_yoloNames.setObjectName("listWidget_yoloNames")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(260, 30, 81, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 280, 101, 17))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_Clear.setText(_translate("Dialog", "Clear"))
        self.groupBox.setTitle(_translate("Dialog", "Config"))
        self.label_6.setText(_translate("Dialog", "batch"))
        self.label_7.setText(_translate("Dialog", "subdivisions"))
        self.label_8.setText(_translate("Dialog", "learning rate"))
        self.label_9.setText(_translate("Dialog", "max_batches"))
        self.btn_Config.setStatusTip(_translate("Dialog", "Config some file"))
        self.btn_Config.setText(_translate("Dialog", "Fix"))
        self.btn_checkCurrent.setStatusTip(_translate("Dialog", "Check current parameter"))
        self.btn_checkCurrent.setText(_translate("Dialog", "Check"))
        self.lineEdit_filter.setStatusTip(_translate("Dialog", "n_filter= (n_class + 5) *3"))
        self.label_10.setText(_translate("Dialog", "Classes"))
        self.label_11.setText(_translate("Dialog", "Filter"))
        self.btn_convert.setStatusTip(_translate("Dialog", "Convert to unix format"))
        self.btn_convert.setText(_translate("Dialog", "Convert"))
        self.btn_make.setStatusTip(_translate("Dialog", "make file darknet"))
        self.btn_make.setText(_translate("Dialog", "Make"))
        self.groupBox_3.setTitle(_translate("Dialog", "data & names"))
        self.label.setText(_translate("Dialog", "yolo.names"))
        self.label_2.setText(_translate("Dialog", "yolo.data"))
        self.label_3.setText(_translate("Dialog", "Information"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
